name: Test workflow # nombre del workflow

on: [pull_request] # evento que dispara el wf

jobs:
  tests: # nombre del job / proceos a disparar
    runs-on: ubuntu-latest # donde correra

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2 # Descarga el código del repositorio en el entorno de ejecución usando la acción actions/checkout@v2.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 #  descarga e instala Node.js.
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Run test and report issues #codecov
        run: npm run test